namespace RE4R.AP.Launcher.Core.Models;

/// <summary>
/// The apworld's merchant shop checks (D4), read from slot_data at scout time.
///
/// The apworld resolves each check AFTER fill, so slot_data already names the
/// item and its owner: the launcher never has to scout the shop or fetch a
/// datapackage to print the merchant's shelf.
///
/// With rotation, checks outnumber the shelf. The apworld releases checks per
/// chapter (up to 90) while the game has exactly 20 usable stand-in item ids,
/// so a row is a DISPLAY WINDOW that carries several checks across a run
/// rather than a permanent home for one. The launcher owns the row ids and the
/// per-check message GUIDs, and hands both to the two consumers: the BioRand
/// fork (rows and baked text, via the ap-merchant-shop manifest section) and
/// the in-game mod (which check a row currently shows, via the room file's
/// merchant_shop section).
///
/// Rooms generated by older apworlds have no merchant_shop block and read as
/// disabled, which leaves the merchant exactly as he was.
/// </summary>
public sealed class MerchantShopSlotData
{
    public static readonly MerchantShopSlotData Disabled = new();

    public bool Enabled { get; init; }

    public IReadOnlyList<MerchantShopSlot> Slots { get; init; } = Array.Empty<MerchantShopSlot>();

    /// <summary>
    /// Engine item ids of merchant gear the multiworld holds instead of the
    /// shelf (D10, ShuffleMerchantGear). The fork strips these from the
    /// shop's stock through the same exclusion the pool-unique buyables use.
    /// Empty for rooms without the option.
    /// </summary>
    public IReadOnlyList<int> ScatteredItemIds { get; init; } = Array.Empty<int>();

    /// <summary>
    /// [Starting Arsenal] Engine ids the player begins with (precollected by
    /// the multiworld). The fork paces their ammo from chapter zero. Empty
    /// for rooms without the option.
    /// </summary>
    public IReadOnlyList<int> StartingWeaponIds { get; init; } = Array.Empty<int>();

    /// <summary>
    /// Credit-check economy per AP classification: the peseta price of a slot
    /// and the gemstone handed back when the purchase is refundable. The
    /// apworld owns these values (shop.SHOP_TIERS); the launcher passes them
    /// through so there is exactly one source of truth.
    /// </summary>
    public IReadOnlyDictionary<string, MerchantShopTier> Tiers { get; init; }
        = new Dictionary<string, MerchantShopTier>(StringComparer.OrdinalIgnoreCase);
}

public sealed class MerchantShopSlot
{
    public long LocationCode { get; init; }

    public int Index { get; init; }

    /// <summary>
    /// The check's durable key ("shop:chapter:3:check:2"). Keyed on the check
    /// itself, never on the row displaying it, so rotation can move a check
    /// between rows without losing its acknowledgement. Rooms from before
    /// rotation carry no identity and fall back to "shop:slot:&lt;index&gt;",
    /// which is exactly what those rooms already acked against.
    /// </summary>
    public string Identity { get; init; } = string.Empty;

    /// <summary>Chapter the check is released in (logic counts it one later).</summary>
    public int UnlockChapter { get; init; }

    /// <summary>1-based position within its own chapter's release batch.</summary>
    public int ChapterOrdinal { get; init; } = 1;

    /// <summary>
    /// Engine item id behind a LOCAL check, so the row can wear the real
    /// item's name, caption, icon and model instead of the [AP] stand-in
    /// dressing. Zero for remote checks (they have no RE4R id, which is why
    /// they keep the AP dressing) and for anything the item table cannot name.
    /// </summary>
    public int ItemId { get; init; }

    /// <summary>How many the local item's AP name promises ("x16" is 16).</summary>
    public int ItemStack { get; init; }

    /// <summary>What the slot holds, as the multiworld names it.</summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>Who owns it - the buying player for a local item.</summary>
    public string PlayerName { get; init; } = string.Empty;

    /// <summary>PROGRESSION | USEFUL | FILLER - picks the price/refund tier.</summary>
    public string Classification { get; init; } = "FILLER";

    /// <summary>True when the item belongs to another player.</summary>
    public bool Remote { get; init; }
}

public sealed record MerchantShopTier(int Price, int RefundItemId, string RefundItemName);
