namespace RE4R.AP.Launcher.Core.Models;

/// <summary>
/// The apworld's merchant shop checks (D4), read from slot_data at scout time.
///
/// The apworld resolves each slot AFTER fill, so slot_data already names the
/// item and its owner: the launcher never has to scout the shop or fetch a
/// datapackage to print the merchant's shelf. The launcher's own job is to
/// assign each slot a stand-in engine item id, then hand the result to two
/// consumers - the BioRand fork (catalog rows, via the ap-merchant-shop
/// manifest section) and the in-game mod (purchase handling, via the room
/// file's merchant_shop section).
///
/// Rooms generated by older apworlds have no merchant_shop block and read as
/// disabled, which leaves the merchant exactly as he was.
/// </summary>
public sealed class MerchantShopSlotData
{
    public static readonly MerchantShopSlotData Disabled = new();

    public bool Enabled { get; init; }

    public IReadOnlyList<MerchantShopSlot> Slots { get; init; } = Array.Empty<MerchantShopSlot>();

    /// <summary>
    /// Engine item ids of merchant gear the multiworld holds instead of the
    /// shelf (D10, ShuffleMerchantGear). The fork strips these from the
    /// shop's stock through the same exclusion the pool-unique buyables use.
    /// Empty for rooms without the option.
    /// </summary>
    public IReadOnlyList<int> ScatteredItemIds { get; init; } = Array.Empty<int>();

    /// <summary>
    /// Credit-check economy per AP classification: the peseta price of a slot
    /// and the gemstone handed back when the purchase is refundable. The
    /// apworld owns these values (shop.SHOP_TIERS); the launcher passes them
    /// through so there is exactly one source of truth.
    /// </summary>
    public IReadOnlyDictionary<string, MerchantShopTier> Tiers { get; init; }
        = new Dictionary<string, MerchantShopTier>(StringComparer.OrdinalIgnoreCase);
}

public sealed class MerchantShopSlot
{
    public long LocationCode { get; init; }

    public int Index { get; init; }

    /// <summary>Chapter the shop row appears in (logic counts it one later).</summary>
    public int UnlockChapter { get; init; }

    /// <summary>What the slot holds, as the multiworld names it.</summary>
    public string DisplayName { get; init; } = string.Empty;

    /// <summary>Who owns it - the buying player for a local item.</summary>
    public string PlayerName { get; init; } = string.Empty;

    /// <summary>PROGRESSION | USEFUL | FILLER - picks the price/refund tier.</summary>
    public string Classification { get; init; } = "FILLER";

    /// <summary>True when the item belongs to another player.</summary>
    public bool Remote { get; init; }
}

public sealed record MerchantShopTier(int Price, int RefundItemId, string RefundItemName);
