namespace RE4R.AP.Launcher.Core.Models;

/// <summary>
/// The apworld's AP-authored Random Events choice, read from slot_data at
/// scout time. When enabled, <see cref="ChosenEvents"/> is the COMPLETE event
/// set the multiworld rolled at generation: ManifestBuilder pins it into the
/// BioRand fork as <c>ap-forced-events</c> (with <c>ap-event-data-hash</c> so
/// drifted event CSVs fail the patch loudly), and forces the three BioRand
/// switches the events machinery needs. Rooms generated by older apworlds
/// have no random_events block and read as disabled.
/// </summary>
public sealed class RandomEventsSlotData
{
    public static readonly RandomEventsSlotData Disabled = new();

    public bool Enabled { get; init; }

    public IReadOnlyList<string> ChosenEvents { get; init; } = Array.Empty<string>();

    public string? EventDataHash { get; init; }

    /// <summary>
    /// AP location codes the roll deleted from the world (an event can remove
    /// a pickup outright). The room scouts this many fewer locations than the
    /// bundled static data lists.
    /// </summary>
    public IReadOnlyList<long> RemovedLocationCodes { get; init; } = Array.Empty<long>();
}
