namespace RE4R.AP.Launcher.Core.Models;

/// <summary>
/// The apworld's Trade-tab checks (Phase 2 of the Trade takeover), read from
/// slot_data at scout time.
///
/// Same contract shape as the merchant shop: the apworld resolves every check
/// AFTER fill, so slot_data already names each check's item and owner and the
/// launcher never scouts the tab or fetches a datapackage to print it.
///
/// Checks rotate through the tab's fixed slot budget at runtime (the 32-entry
/// per-save claim array, ids 0-31, measured live 2026-08-31), so check count
/// is independent of slot count. Prices are SPINEL, tier-fixed per check at
/// generation; trade checks never refund. The exchange economy rides along:
/// the infinite Velvet Blue and the three restocking gems, at the 2026-08-31
/// rates (one spinel over par, VaporeonMega's haircut).
///
/// Rooms generated by older apworlds have no trade_shop block and read as
/// disabled, which leaves the Trade tab exactly as BioRand made it.
/// </summary>
public sealed class TradeShopSlotData
{
    public static readonly TradeShopSlotData Disabled = new();

    public bool Enabled { get; init; }

    public IReadOnlyList<TradeShopCheck> Checks { get; init; } = Array.Empty<TradeShopCheck>();

    /// <summary>Spinel price of the infinite Velvet Blue slot.</summary>
    public int VelvetBlueSpinel { get; init; }

    /// <summary>The gem slots: name -> (engine item id, spinel price).</summary>
    public IReadOnlyDictionary<string, TradeShopGem> Gems { get; init; }
        = new Dictionary<string, TradeShopGem>(StringComparer.OrdinalIgnoreCase);

    /// <summary>Spinel's engine item id (the wallet currency).</summary>
    public int SpinelItemId { get; init; }

    /// <summary>How much Spinel the pool mints (the exact sum of check prices).</summary>
    public int SpinelPoolTotal { get; init; }

    /// <summary>
    /// Engine ids of the vanilla trade stock the multiworld holds instead of
    /// the tab (the strip list for the fork). Empty for rooms without the
    /// merchant shuffle.
    /// </summary>
    public IReadOnlyList<int> ShuffledTradeItemIds { get; init; } = Array.Empty<int>();
}

public sealed class TradeShopCheck
{
    public long LocationCode { get; init; }

    /// <summary>1-based position in release order, stable forever.</summary>
    public int ReleaseIndex { get; init; }

    /// <summary>The durable key ("trade:chapter:3:check:2").</summary>
    public string Identity { get; init; } = string.Empty;

    /// <summary>The chapter that releases it.</summary>
    public int Chapter { get; init; }

    public int ChapterOrdinal { get; init; } = 1;

    /// <summary>Spinel price, tier-fixed at generation.</summary>
    public int PriceSpinel { get; init; }

    /// <summary>FILLER | USEFUL | PROGRESSION - names the price tier only.</summary>
    public string Tier { get; init; } = "FILLER";

    /// <summary>
    /// Sum of prices through this check in release order; the apworld's
    /// logic threshold, carried for display and diagnostics.
    /// </summary>
    public int CumulativeSpinel { get; init; }

    /// <summary>
    /// Engine item id behind a LOCAL check so the slot can wear the real
    /// item's dressing; zero for remote checks and unknown items.
    /// </summary>
    public int ItemId { get; init; }

    public int ItemStack { get; init; }

    public string DisplayName { get; init; } = string.Empty;

    public string PlayerName { get; init; } = string.Empty;

    public bool Remote { get; init; }
}

public sealed record TradeShopGem(int ItemId, int Spinel);
