-- [Welcome note window] The in-game welcome note, reopened on demand from the
-- Guidance tab ("Show the welcome note"). Styled like the progression-warning
-- dialog (centred, its own window) rather than buried inside a tab.
--
-- Since 2026-09-05 the pages ARE the note: welcome_note.json is generated by
-- welcome_note.py from the same data/welcome_note.txt the fork bakes into the
-- in-world document, so the window and the paper can never disagree. The
-- three short pages below are only the fallback for a data folder that lacks
-- the file (an older payload store).
--
-- First-run teaching belongs to the native in-world book. This window used to
-- arm itself on a seed's first playable Chapter 1 tick, but it can only render
-- inside REFramework's menu, so it ambushed the first Insert of every fresh
-- seed instead of greeting the player (live test 2026-08-16).
local function install(ctx)
    local bridge = ctx.bridge

    local function export(name, value)
        ctx[name] = value
        _G[name] = value
    end

    local WELCOME_NOTE_FILE = "ArchipelagoRE4R\\welcome_note.json"

    -- Pages keep each screen short; a wall of text gets dismissed unread.
    local FALLBACK_PAGES = {
        {
            title = "Welcome to Resident Evil 4 in Archipelago",
            lines = {
                "Your item pickups are now checks. Collecting one sends an item",
                "to another player in the multiworld, and their finds send items",
                "to you - weapons, herbs, key items, anything.",
                "",
                "Items belonging to other players appear in the world as the",
                "Archipelago logo. Grab them like any other pickup: they go to",
                "their owner, not into your inventory.",
            },
        },
        {
            title = "Finding your checks",
            lines = {
                "Unchecked spots show a floating [AP] Marker with the distance,",
                "the chapter it belongs to, and how far above or below you it is.",
                "",
                "The Guidance tab turns Markers on or off, sets how far away they",
                "appear, and can make them more detailed - up to naming the item",
                "you would be finding.",
                "",
                "The on-screen header always shows your area and how many checks",
                "you have found there.",
            },
        },
        {
            title = "When you get stuck",
            lines = {
                "Press Insert at any time to open or close the Archipelago",
                "window (this is REFramework's menu key).",
                "",
                "The Checklist tab lists every save point with how many checks",
                "are still waiting near it - and warps you there once you have",
                "visited it.",
                "",
                "The Hints tab spends hint points to reveal where an item is.",
                "A hint inside your own world lights up that spot; a hint for one",
                "of your items in someone else's world is pinned on screen under",
                "\"Multiworld Hints\", naming the player who has it.",
                "",
                "Something's Wrong has the recovery tools if a check refuses to",
                "send. Waiting on another player is normal in a multiworld: your",
                "next key item may be in someone else's game.",
            },
        },
    }

    local pages = nil
    local pages_from_file = false

    -- Read welcome_note.json; fall back to the built-in pages. Called on every
    -- reopen, so a data folder refreshed by a patch is picked up without a
    -- restart, and a missing file never leaves the button doing nothing.
    local function load_pages()
        local ok, payload = pcall(json.load_file, WELCOME_NOTE_FILE)
        if ok and type(payload) == "table" and type(payload.pages) == "table" then
            local loaded = {}
            for _, raw in ipairs(payload.pages) do
                if type(raw) == "table" then
                    local lines = {}
                    for _, text in ipairs(raw.lines or {}) do
                        lines[#lines + 1] = tostring(text)
                    end
                    loaded[#loaded + 1] = {
                        title = (type(raw.title) == "string" and raw.title ~= "") and raw.title or nil,
                        title_color = tonumber(raw.title_color),
                        lines = lines,
                    }
                end
            end
            if #loaded > 0 then
                pages = loaded
                pages_from_file = true
                return
            end
        end
        pages = FALLBACK_PAGES
        pages_from_file = false
    end

    -- The note greets the player by slot name; the window does the same.
    local function slot_name()
        local name = bridge.ap_session_slot_name
        if type(name) ~= "string" or name == "" then
            return "Player"
        end
        return name
    end

    local function draw_tutorial_dialog()
        if not bridge.tutorial_dialog_open then
            return
        end
        -- Only draw while REFramework's menu is open (Insert), where there is a
        -- free cursor and imgui receives the clicks. During gameplay the game
        -- captures the mouse for camera-look, so buttons fell through to it -
        -- that was the "mouse falls through" bug. The native in-world book is
        -- the first-run tutorial now; this popup is the reopen-from-Guidance
        -- version, which is always opened from inside the menu anyway.
        local ok_ui, drawing_ui = pcall(function() return reframework:is_drawing_ui() end)
        if not ok_ui or not drawing_ui then
            return
        end
        local state = bridge.last_state or {}
        if not state.is_in_game then
            return
        end
        if pages == nil then
            load_pages()
        end

        local page_index = math.max(1, math.min(#pages, math.floor(tonumber(bridge.tutorial_page) or 1)))
        local page = pages[page_index]

        -- Wide enough for the 78-column lines welcome_note.py wraps to, tall
        -- enough that a typical page needs no scrolling; the body is a
        -- scrolling panel, so the longest pages (Known Issues, Credits) still
        -- fit without clipping the buttons, which sit above it on purpose.
        local dialog_width = 760
        local dialog_height = 560
        local pos_x, pos_y = 80, 80
        local ok_display, display_size = pcall(function()
            return imgui.get_display_size()
        end)
        if ok_display and display_size ~= nil then
            pos_x = math.max(40, ((tonumber(display_size.x or 0) - dialog_width) * 0.5))
            pos_y = math.max(40, ((tonumber(display_size.y or 0) - dialog_height) * 0.35))
        end

        imgui.set_next_window_pos(Vector2f.new(pos_x, pos_y), 1)
        imgui.set_next_window_size(Vector2f.new(dialog_width, dialog_height), 1)

        local visible = imgui.begin_window("Archipelago - Welcome Note", true, nil)
        if not visible then
            bridge.tutorial_dialog_open = false
            bridge.tutorial_shown = true
            imgui.end_window()
            return
        end

        local theme = ctx.theme
        local title = page.title or "Resident Evil 4 - Archipelago"
        if theme ~= nil and type(theme.colored) == "function" and page.title_color ~= nil then
            theme.colored(title, page.title_color)
        else
            imgui.text(title)
        end
        imgui.same_line()
        imgui.text(string.format("   page %d of %d", page_index, #pages))

        -- Navigation above the body, so a long page can scroll without
        -- pushing the buttons off the window.
        if page_index > 1 then
            if imgui.button("Back##ap_note_back") then
                bridge.tutorial_page = page_index - 1
            end
            imgui.same_line()
        end
        if page_index < #pages then
            if imgui.button("Next##ap_note_next") then
                bridge.tutorial_page = page_index + 1
            end
            imgui.same_line()
        end
        if imgui.button("Close##ap_note_close") then
            bridge.tutorial_dialog_open = false
            bridge.tutorial_shown = true
        end
        if not pages_from_file then
            imgui.same_line()
            imgui.text("   (short guide: welcome_note.json not found, re-patch to get the full note)")
        end
        if theme ~= nil and type(theme.separator) == "function" then
            theme.separator()
        else
            imgui.text("------------------------------------------------------------")
        end

        local panel = (theme ~= nil and type(theme.begin_panel) == "function") and theme.begin_panel() or { open = false }
        local slot = string.gsub(slot_name(), "%%", "%%%%")
        for _, text in ipairs(page.lines) do
            local line = text
            if string.find(line, "{slot}", 1, true) then
                line = string.gsub(line, "{slot}", slot)
            end
            imgui.text(line)
        end
        if theme ~= nil and type(theme.end_panel) == "function" then
            theme.end_panel(panel)
        end
        imgui.end_window()
    end

    -- Manual replay, offered in Guidance. Reloads the pages every time so a
    -- payload refreshed underneath a running game shows the new note.
    local function replay_tutorial()
        load_pages()
        bridge.tutorial_page = 1
        bridge.tutorial_dialog_open = true
        return pages_from_file and "welcome note opened" or "short guide opened (welcome_note.json missing)"
    end

    export("draw_tutorial_dialog", draw_tutorial_dialog)
    export("replay_tutorial", replay_tutorial)
    export("welcome_note_pages_loaded", function() return pages ~= nil and #pages or 0, pages_from_file end)
end

return install
